name: Update gist with WakaTime stats
on:
  push:
    branches: master  
  schedule:
    - cron: "* */3 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: waka-box
        uses: minibear2333/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 900a84827c42c5f77a17ae8e510ed203
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }} 
