name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "* * * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: waka-box
        uses: matchai/waka-box@v4.0.3
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 900a84827c42c5f77a17ae8e510ed203
